/**
 * Copyright (c) 2016-2019 by the respective copyright holders.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 */
package com.zsmartsystems.zigbee.dongle.zstack.api.zdo;

import com.zsmartsystems.zigbee.dongle.zstack.api.ZstackFrameRequest;
import com.zsmartsystems.zigbee.dongle.zstack.api.rpc.ZstackRpcSreqErrorSrsp;

/**
 * Class to implement the Z-Stack command <b>ZDO_MSG_CB_REGISTER</b>.
 * <p>
 * This command registers for a ZDO callback.
 * <p>
 * Note that this code is autogenerated. Manual changes may be overwritten.
 *
 * @author Chris Jackson
 */
public class ZstackZdoMsgCbRegisterSreq extends ZstackFrameRequest {

    /**
     * Specifies the ZDO Cluster Id for which to receive a ZDO callback.
     */
    private int clusterId;

    /**
     * Request constructor
     */
    public ZstackZdoMsgCbRegisterSreq() {
        synchronousCommand = true;
    }

    /**
     * Specifies the ZDO Cluster Id for which to receive a ZDO callback.
     *
     * @return the current clusterId as {@link int}
     */
    public int getClusterId() {
        return clusterId;
    }

    /**
     * Specifies the ZDO Cluster Id for which to receive a ZDO callback.
     *
     * @param clusterId the ClusterId to set as {@link int}
     */
    public void setClusterId(int clusterId) {
        this.clusterId = clusterId;
    }

    @Override
    public boolean matchSreqError(ZstackRpcSreqErrorSrsp response) {
        return (((response.getReqCmd0() & 0x1F) == ZSTACK_ZDO) && (response.getReqCmd1() == 0x3E));
    }

    @Override
    public int[] serialize() {
        // Serialize the header
        serializeHeader(ZSTACK_SREQ, ZSTACK_ZDO, 0x3E);

        // Serialize the fields
        serializeUInt16(clusterId);
        return getPayload();
    }

    @Override
    public String toString() {
        final StringBuilder builder = new StringBuilder(54);
        builder.append("ZstackZdoMsgCbRegisterSreq [clusterId=");
        builder.append(String.format("%04X", clusterId));
        builder.append(']');
        return builder.toString();
    }
}
