/**
 * Copyright (c) 2016-2019 by the respective copyright holders.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 */
package com.zsmartsystems.zigbee.dongle.zstack.api.appcnf;

import com.zsmartsystems.zigbee.dongle.zstack.api.ZstackFrameRequest;
import com.zsmartsystems.zigbee.dongle.zstack.api.rpc.ZstackRpcSreqErrorSrsp;

/**
 * Class to implement the Z-Stack command <b>APP_CNF_SET_ALLOWREJOIN_TC_POLICY</b>.
 * <p>
 * Sets the AllowRejoin TC policy.
 * <p>
 * Note that this code is autogenerated. Manual changes may be overwritten.
 *
 * @author Chris Jackson
 */
public class ZstackAppCnfSetAllowrejoinTcPolicySreq extends ZstackFrameRequest {

    /**
     * This value specifies whether or not the Trust Center allows devices to rejoin.
     */
    private boolean allowRejoin;

    /**
     * Request constructor
     */
    public ZstackAppCnfSetAllowrejoinTcPolicySreq() {
        synchronousCommand = true;
    }

    /**
     * This value specifies whether or not the Trust Center allows devices to rejoin.
     *
     * @return the current allowRejoin as {@link boolean}
     */
    public boolean getAllowRejoin() {
        return allowRejoin;
    }

    /**
     * This value specifies whether or not the Trust Center allows devices to rejoin.
     *
     * @param allowRejoin the AllowRejoin to set as {@link boolean}
     */
    public void setAllowRejoin(boolean allowRejoin) {
        this.allowRejoin = allowRejoin;
    }

    @Override
    public boolean matchSreqError(ZstackRpcSreqErrorSrsp response) {
        return (((response.getReqCmd0() & 0x1F) == ZSTACK_APP_CNF) && (response.getReqCmd1() == 0x02));
    }

    @Override
    public int[] serialize() {
        // Serialize the header
        serializeHeader(ZSTACK_SREQ, ZSTACK_APP_CNF, 0x02);

        // Serialize the fields
        serializeBoolean(allowRejoin);
        return getPayload();
    }

    @Override
    public String toString() {
        final StringBuilder builder = new StringBuilder(66);
        builder.append("ZstackAppCnfSetAllowrejoinTcPolicySreq [allowRejoin=");
        builder.append(allowRejoin);
        builder.append(']');
        return builder.toString();
    }
}
