/**
 * Copyright (c) 2016-2026 by the respective copyright holders.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 */
package com.zsmartsystems.zigbee.dongle.ember.ezsp.structure;

import java.util.HashMap;
import java.util.Map;

/**
 * Class to implement the Ember Enumeration <b>EzspSecurityManagerKeyType</b>.
 * <p>
 * Note that this code is autogenerated. Manual changes may be overwritten.
 *
 * @author Chris Jackson - Initial contribution of Java code generator
 */
public enum EzspSecurityManagerKeyType {
    /**
     * Default unknown value
     */
    UNKNOWN(-1),

    /**
     * No key type.
     */
    NONE(0x00),

    /**
     * Network key.
     */
    NETWORK(0x01),

    /**
     * Trust Center link key.
     */
    TC_LINK(0x02),

    /**
     * Trust Center link key with timeout.
     */
    TC_LINK_WITH_TIMEOUT(0x03),

    /**
     * Application link key.
     */
    APP_LINK(0x04),

    /**
     * Green Power proxy table key.
     */
    GREEN_POWER_PROXY_TABLE_KEY(0x05),

    /**
     * Green Power sink table key.
     */
    GREEN_POWER_SINK_TABLE_KEY(0x06),

    /**
     * ZLL encryption key.
     */
    ZLL_ENCRYPTION_KEY(0x07),

    /**
     * ZLL preconfigured key.
     */
    ZLL_PRECONFIGURED_KEY(0x08),

    /**
     * Internal key type.
     */
    INTERNAL(0x09);

    /**
     * A mapping between the integer code and its corresponding type to
     * facilitate lookup by code.
     */
    private static Map<Integer, EzspSecurityManagerKeyType> codeMapping;

    private int key;

    static {
        codeMapping = new HashMap<Integer, EzspSecurityManagerKeyType>();
        for (EzspSecurityManagerKeyType s : values()) {
            codeMapping.put(s.key, s);
        }
    }

    private EzspSecurityManagerKeyType(int key) {
        this.key = key;
    }

    /**
     * Lookup function based on the type code. Returns null if the
     * code does not exist.
     *
     * @param code the code to lookup
     * @return enumeration value of the alarm type.
     */
    public static EzspSecurityManagerKeyType getEzspSecurityManagerKeyType(int code) {
        if (codeMapping.get(code) == null) {
            return UNKNOWN;
        }

        return codeMapping.get(code);
    }

    /**
     * Returns the EZSP protocol defined value for this enumeration.
     *
     * @return the EZSP protocol key
     */
    public int getKey() {
        return key;
    }
}
