/**
 * Copyright (c) 2016-2026 by the respective copyright holders.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 */
package com.zsmartsystems.zigbee.dongle.ember.ezsp.structure;

import com.zsmartsystems.zigbee.IeeeAddress;
import com.zsmartsystems.zigbee.dongle.ember.internal.serializer.EzspDeserializer;
import com.zsmartsystems.zigbee.dongle.ember.internal.serializer.EzspSerializer;

/**
 * Class to implement the Ember Structure <b>EzspSecurityManagerContext</b>.
 * <p>
 * Context for the security manager specifying the key type, index, and other properties.
 * <p>
 * Note that this code is autogenerated. Manual changes may be overwritten.
 *
 * @author Chris Jackson - Initial contribution of Java code generator
 */
public class EzspSecurityManagerContext {

    /**
     * The type of key being referenced.
     * <p>
     * EZSP type is <i>EzspSecurityManagerKeyType</i> - Java type is {@link EzspSecurityManagerKeyType}
     */
    private EzspSecurityManagerKeyType keyType;

    /**
     * The index of the referenced key.
     * <p>
     * EZSP type is <i>uint8_t</i> - Java type is {@link int}
     */
    private int keyIndex;

    /**
     * The type of derivation used to derive the referenced key.
     * <p>
     * EZSP type is <i>uint16_t</i> - Java type is {@link int}
     */
    private int derivedType;

    /**
     * The EUI64 associated with this key.
     * <p>
     * EZSP type is <i>EmberEUI64</i> - Java type is {@link IeeeAddress}
     */
    private IeeeAddress eui64;

    /**
     * The multi-network index for this key.
     * <p>
     * EZSP type is <i>uint8_t</i> - Java type is {@link int}
     */
    private int multiNetworkIndex;

    /**
     * Flags associated with this key.
     * <p>
     * EZSP type is <i>uint8_t</i> - Java type is {@link int}
     */
    private int flags;

    /**
     * The PSA key algorithm permission.
     * <p>
     * EZSP type is <i>uint32_t</i> - Java type is {@link int}
     */
    private int psaKeyAlgPermission;

    /**
     * Default Constructor
     */
    public EzspSecurityManagerContext() {
    }

    public EzspSecurityManagerContext(EzspDeserializer deserializer) {
        deserialize(deserializer);
    }

    /**
     * The type of key being referenced.
     * <p>
     * EZSP type is <i>EzspSecurityManagerKeyType</i> - Java type is {@link EzspSecurityManagerKeyType}
     *
     * @return the current keyType as {@link EzspSecurityManagerKeyType}
     */
    public EzspSecurityManagerKeyType getKeyType() {
        return keyType;
    }

    /**
     * The type of key being referenced.
     *
     * @param keyType the keyType to set as {@link EzspSecurityManagerKeyType}
     */
    public void setKeyType(EzspSecurityManagerKeyType keyType) {
        this.keyType = keyType;
    }

    /**
     * The index of the referenced key.
     * <p>
     * EZSP type is <i>uint8_t</i> - Java type is {@link int}
     *
     * @return the current keyIndex as {@link int}
     */
    public int getKeyIndex() {
        return keyIndex;
    }

    /**
     * The index of the referenced key.
     *
     * @param keyIndex the keyIndex to set as {@link int}
     */
    public void setKeyIndex(int keyIndex) {
        this.keyIndex = keyIndex;
    }

    /**
     * The type of derivation used to derive the referenced key.
     * <p>
     * EZSP type is <i>uint16_t</i> - Java type is {@link int}
     *
     * @return the current derivedType as {@link int}
     */
    public int getDerivedType() {
        return derivedType;
    }

    /**
     * The type of derivation used to derive the referenced key.
     *
     * @param derivedType the derivedType to set as {@link int}
     */
    public void setDerivedType(int derivedType) {
        this.derivedType = derivedType;
    }

    /**
     * The EUI64 associated with this key.
     * <p>
     * EZSP type is <i>EmberEUI64</i> - Java type is {@link IeeeAddress}
     *
     * @return the current eui64 as {@link IeeeAddress}
     */
    public IeeeAddress getEui64() {
        return eui64;
    }

    /**
     * The EUI64 associated with this key.
     *
     * @param eui64 the eui64 to set as {@link IeeeAddress}
     */
    public void setEui64(IeeeAddress eui64) {
        this.eui64 = eui64;
    }

    /**
     * The multi-network index for this key.
     * <p>
     * EZSP type is <i>uint8_t</i> - Java type is {@link int}
     *
     * @return the current multiNetworkIndex as {@link int}
     */
    public int getMultiNetworkIndex() {
        return multiNetworkIndex;
    }

    /**
     * The multi-network index for this key.
     *
     * @param multiNetworkIndex the multiNetworkIndex to set as {@link int}
     */
    public void setMultiNetworkIndex(int multiNetworkIndex) {
        this.multiNetworkIndex = multiNetworkIndex;
    }

    /**
     * Flags associated with this key.
     * <p>
     * EZSP type is <i>uint8_t</i> - Java type is {@link int}
     *
     * @return the current flags as {@link int}
     */
    public int getFlags() {
        return flags;
    }

    /**
     * Flags associated with this key.
     *
     * @param flags the flags to set as {@link int}
     */
    public void setFlags(int flags) {
        this.flags = flags;
    }

    /**
     * The PSA key algorithm permission.
     * <p>
     * EZSP type is <i>uint32_t</i> - Java type is {@link int}
     *
     * @return the current psaKeyAlgPermission as {@link int}
     */
    public int getPsaKeyAlgPermission() {
        return psaKeyAlgPermission;
    }

    /**
     * The PSA key algorithm permission.
     *
     * @param psaKeyAlgPermission the psaKeyAlgPermission to set as {@link int}
     */
    public void setPsaKeyAlgPermission(int psaKeyAlgPermission) {
        this.psaKeyAlgPermission = psaKeyAlgPermission;
    }

    /**
     * Serialise the contents of the EZSP structure.
     *
     * @param serializer the {@link EzspSerializer} used to serialize
     */
    public int[] serialize(EzspSerializer serializer) {
        // Serialize the fields
        serializer.serializeUInt8(keyType.getKey());
        serializer.serializeUInt8(keyIndex);
        serializer.serializeUInt16(derivedType);
        serializer.serializeEmberEui64(eui64);
        serializer.serializeUInt8(multiNetworkIndex);
        serializer.serializeUInt8(flags);
        serializer.serializeUInt32(psaKeyAlgPermission);
        return serializer.getPayload();
    }

    /**
     * Deserialise the contents of the EZSP structure.
     *
     * @param deserializer the {@link EzspDeserializer} used to deserialize
     */
    public void deserialize(EzspDeserializer deserializer) {
        // Deserialize the fields
        keyType = EzspSecurityManagerKeyType.getEzspSecurityManagerKeyType(deserializer.deserializeUInt8());
        keyIndex = deserializer.deserializeUInt8();
        derivedType = deserializer.deserializeUInt16();
        eui64 = deserializer.deserializeEmberEui64();
        multiNetworkIndex = deserializer.deserializeUInt8();
        flags = deserializer.deserializeUInt8();
        psaKeyAlgPermission = deserializer.deserializeUInt32();
    }

    @Override
    public String toString() {
        final StringBuilder builder = new StringBuilder(256);
        builder.append("EzspSecurityManagerContext [keyType=");
        builder.append(keyType);
        builder.append(", keyIndex=");
        builder.append(keyIndex);
        builder.append(", derivedType=");
        builder.append(String.format("%04X", derivedType));
        builder.append(", eui64=");
        builder.append(eui64);
        builder.append(", multiNetworkIndex=");
        builder.append(multiNetworkIndex);
        builder.append(", flags=");
        builder.append(String.format("%02X", flags));
        builder.append(", psaKeyAlgPermission=");
        builder.append(String.format("%08X", psaKeyAlgPermission));
        builder.append(']');
        return builder.toString();
    }
}
