/**
 * Copyright (c) 2014-2017 by the respective copyright holders.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 */
package com.zsmartsystems.zigbee.dongle.ember.ezsp;

import com.zsmartsystems.zigbee.dongle.ember.ezsp.EzspFrameRequest;
import com.zsmartsystems.zigbee.dongle.ember.ezsp.serializer.EzspSerializer;
import java.util.HashMap;
import java.util.Map;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Class to implement the Ember EZSP command <b>idConflictHandler</b>.
 * <p>
 * A callback invoked by the EmberZNet stack when an id conflict is discovered, that is, two
 * different nodes in the network were found to be using the same short id. The stack automatically
 * removes the conflicting short id from its internal tables (address, binding, route,
 * neighbor, and child tables). The application should discontinue any other use of the id.
 * <p>
 * This class provides methods for processing EZSP commands.
 * <p>
 * Note that this code is autogenerated. Manual changes may be overwritten.
 *
 * @author Chris Jackson - Initial contribution of Java code generator
 */
public class EzspIdConflictHandlerRequest extends EzspFrameRequest {
    private static final Logger logger = LoggerFactory.getLogger(EzspIdConflictHandlerRequest.class);

    private EzspSerializer serializer;

    /**
     * Request constructor
     */
    public EzspIdConflictHandlerRequest() {
        serializer = new EzspSerializer();
    }

    @Override
    public int[] serialize() {
        return serializer.getPayload();
    }

    @Override
    public String toString() {
        final StringBuilder builder = new StringBuilder();
        builder.append("]");
        return builder.toString();
    }
}
