/**
 * Copyright (c) 2016-2026 by the respective copyright holders.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 */
package com.zsmartsystems.zigbee.dongle.ember.ezsp.command;

import com.zsmartsystems.zigbee.dongle.ember.ezsp.EzspFrameRequest;
import com.zsmartsystems.zigbee.dongle.ember.ezsp.structure.EzspSecurityManagerContext;
import com.zsmartsystems.zigbee.dongle.ember.internal.serializer.EzspSerializer;

/**
 * Class to implement the Ember EZSP command <b>secManCheckKeyContext</b>.
 * <p>
 * Checks that the passed security manager context is valid.
 * <p>
 * This class provides methods for processing EZSP commands.
 * <p>
 * Note that this code is autogenerated. Manual changes may be overwritten.
 *
 * @author Chris Jackson - Initial contribution of Java code generator
 */
public class EzspSecManCheckKeyContextRequest extends EzspFrameRequest {
    public static final int FRAME_ID = 0x0110;

    /**
     * The security manager context to check.
     * <p>
     * EZSP type is <i>EzspSecurityManagerContext</i> - Java type is {@link EzspSecurityManagerContext}
     */
    private EzspSecurityManagerContext context;

    /**
     * Serialiser used to serialise to binary line data
     */
    private EzspSerializer serializer;

    /**
     * Request constructor
     */
    public EzspSecManCheckKeyContextRequest() {
        frameId = FRAME_ID;
        serializer = new EzspSerializer();
    }

    /**
     * The security manager context to check.
     * <p>
     * EZSP type is <i>EzspSecurityManagerContext</i> - Java type is {@link EzspSecurityManagerContext}
     *
     * @return the current context as {@link EzspSecurityManagerContext}
     */
    public EzspSecurityManagerContext getContext() {
        return context;
    }

    /**
     * The security manager context to check.
     *
     * @param context the context to set as {@link EzspSecurityManagerContext}
     */
    public void setContext(EzspSecurityManagerContext context) {
        this.context = context;
    }

    @Override
    public int[] serialize() {
        // Serialize the header
        serializeHeader(serializer);

        // Serialize the fields
        context.serialize(serializer);
        return serializer.getPayload();
    }

    @Override
    public String toString() {
        final StringBuilder builder = new StringBuilder(96);
        builder.append("EzspSecManCheckKeyContextRequest [networkId=");
        builder.append(networkId);
        builder.append(", context=");
        builder.append(context);
        builder.append(']');
        return builder.toString();
    }
}
