/**
 * Copyright (c) 2016-2026 by the respective copyright holders.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 */
package com.zsmartsystems.zigbee.dongle.ember.ezsp.command;

import com.zsmartsystems.zigbee.dongle.ember.ezsp.EzspFrameResponse;

/**
 * Class to implement the Ember EZSP command <b>secManImportTransientKey</b>.
 * <p>
 * Imports a transient key for a device into the security manager.
 * <p>
 * This class provides methods for processing EZSP commands.
 * <p>
 * Note that this code is autogenerated. Manual changes may be overwritten.
 *
 * @author Chris Jackson - Initial contribution of Java code generator
 */
public class EzspSecManImportTransientKeyResponse extends EzspFrameResponse {
    public static final int FRAME_ID = 0x0111;

    /**
     * The success or failure code of the operation.
     * <p>
     * EZSP type is <i>sl_status_t</i> - Java type is {@link int}
     */
    private int slStatus;

    /**
     * Response and Handler constructor
     */
    public EzspSecManImportTransientKeyResponse(int[] inputBuffer) {
        // Super creates deserializer and reads header fields
        super(inputBuffer);

        // Deserialize the fields
        slStatus = deserializer.deserializeUInt32();
    }

    /**
     * The success or failure code of the operation.
     * <p>
     * EZSP type is <i>sl_status_t</i> - Java type is {@link int}
     *
     * @return the current slStatus as {@link int}
     */
    public int getSlStatus() {
        return slStatus;
    }

    /**
     * The success or failure code of the operation.
     *
     * @param slStatus the slStatus to set as {@link int}
     */
    public void setSlStatus(int slStatus) {
        this.slStatus = slStatus;
    }

    @Override
    public String toString() {
        final StringBuilder builder = new StringBuilder(96);
        builder.append("EzspSecManImportTransientKeyResponse [networkId=");
        builder.append(networkId);
        builder.append(", slStatus=");
        builder.append(String.format("%08X", slStatus));
        builder.append(']');
        return builder.toString();
    }
}
